// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS0W44NEw72m_4m4dPBUvEbpYhVIGqyz8',
    appId: '1:374077731736:web:16fbe49e529656dd37f1ed',
    messagingSenderId: '374077731736',
    projectId: 'jarnama-app-c982c',
    authDomain: 'jarnama-app-c982c.firebaseapp.com',
    storageBucket: 'jarnama-app-c982c.appspot.com',
    measurementId: 'G-15S3K070KB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu5uHzuWegqUm6yQdPCYjue6bL06GKCkg',
    appId: '1:374077731736:android:6c2bf6ed699d990037f1ed',
    messagingSenderId: '374077731736',
    projectId: 'jarnama-app-c982c',
    storageBucket: 'jarnama-app-c982c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOfzaADi4pkGP96Y2rXYq-mB6gSgEq_ws',
    appId: '1:374077731736:ios:eb0b955a88bd987737f1ed',
    messagingSenderId: '374077731736',
    projectId: 'jarnama-app-c982c',
    storageBucket: 'jarnama-app-c982c.appspot.com',
    iosClientId: '374077731736-uhr1kgv0nk0i9silm259hss3i3a2qn4d.apps.googleusercontent.com',
    iosBundleId: 'com.example.jarnamaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOfzaADi4pkGP96Y2rXYq-mB6gSgEq_ws',
    appId: '1:374077731736:ios:eb0b955a88bd987737f1ed',
    messagingSenderId: '374077731736',
    projectId: 'jarnama-app-c982c',
    storageBucket: 'jarnama-app-c982c.appspot.com',
    iosClientId: '374077731736-uhr1kgv0nk0i9silm259hss3i3a2qn4d.apps.googleusercontent.com',
    iosBundleId: 'com.example.jarnamaApp',
  );
}
